language: erlang

notifications:
  email: ruan800@gmail.com

before_script:
  kerl list installations

otp_release:
    - 17.5
    - 17.5.6.10
    - 18.3
    - 18.3.4.11
    - 19.3
    - 19.3.6.13
    - 20.3
    - 20.3.8.26
    - 21.3
    - 21.3.8.21
    - 22.3
    - 22.3.4.16
    - 23.3

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

script:
  epmd -daemon && make && ./rebar3 eunit -v -c && ./rebar3 ct -c --readable true --verbose && ./rebar3 cover -v && ./rebar3 coveralls send

env:
  global:
    - TIMEOUT=100

dist: trusty

