case os:getenv("TRAVIS") of
  "true" ->
    JobId = os:getenv("TRAVIS_JOB_ID"),
    io:format("TRAVIS_JOB_ID ============>  ~p  <-----------\n", [JobId]),
    C = lists:keystore(coveralls_service_job_id, 1, CONFIG, {coveralls_service_job_id, JobId}),
    io:format("Config!!!!!!!!!!!!!!!!!! ~p\n", [C]),
    C;
  _ ->
    io:format("WHAT THE HELLL!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n", []),
    CONFIG
end.